# Generated by Django 4.2.7 on 2024-03-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_subscribe'),
        ('publicate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='post',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='post',
            field=models.ManyToManyField(to='publicate.post'),
        ),
    ]
