# Generated by Django 4.2.7 on 2024-04-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publicate.category'),
        ),
        migrations.AddField(
            model_name='cart',
            name='post',
            field=models.ManyToManyField(null=True, to='publicate.post'),
        ),
    ]
