# Generated by Django 4.2.7 on 2024-03-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0006_rename_product_cart_post_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicate.post'),
        ),
    ]
