# Generated by Django 4.2.7 on 2024-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0009_like_created_at_alter_like_post_commentcommenting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
