# Generated by Django 4.2.7 on 2024-03-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0010_like_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentCommenting',
        ),
    ]
