# Generated by Django 4.2.7 on 2024-03-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0012_alter_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='rating',
        ),
    ]
