# Generated by Django 4.2.7 on 2024-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0013_remove_like_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
