# Generated by Django 4.2.7 on 2024-03-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0014_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
