# Generated by Django 4.2.7 on 2024-03-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0018_rename_timestamp_cart_created_at_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
