# Generated by Django 4.2.7 on 2024-03-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0019_remove_like_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
