# Generated by Django 4.2.7 on 2024-03-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0023_remove_cart_created_at_remove_cart_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='rating',
        ),
    ]
