# Generated by Django 4.2.7 on 2024-03-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0024_remove_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
