# Generated by Django 4.2.7 on 2024-03-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicate', '0026_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
