# Generated by Django 4.2.10 on 2024-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_myuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='subscribe',
            field=models.IntegerField(default=0),
        ),
    ]
